### ISSUE TITLE
Maybe you should clarify that it has nothing to do with the /.well-known/ URIs

### ISSUE THREAD

**Issue by HenkPoley** [FriendsOfPHP/well-known-implementations#5]
E.g. https://en.wikipedia.org/wiki/Well-known_URI

Not sure if strictly necessary, but it made me think of that thing first.

**Comment by nicolas-grekas** [comment]
It has nothing to do with URLs of course. Conceptually, it's still similar, just in another domain. The current name sticks to me :)
